Get list of all files in PR

diff --git a/.github/workflows/validation.yaml b/.github/workflows/validation.yaml
--- a/.github/workflows/validation.yaml
+++ b/.github/workflows/validation.yaml
@@ -1,23 +1,16 @@
-
 name: Validation
 
 on:
-  pull_request:
-    branches: [ main ]
-  push:
-    branches: [ main ]
+  - pull_request
 
 jobs:
   validate-tds:
     name: Validate TDs
-
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout wot-testing
         uses: actions/checkout@v2
-        with:
-          fetch-depth: 2
                      
       - name: Checkout thingweb-playground
         uses: actions/checkout@v2
@@ -35,20 +28,25 @@ jobs:
         run: npm install
 
       - name: Run validation script on all new matching files
-        # run: |
-        #   git diff --name-only HEAD HEAD~1 | \
-        #   grep ".*\.td.jsonld$" | \
-        #   xargs -i node thingweb-playground/packages/cli/index.js {}
+        env:
+          VALIDATION_SCRIPT: thingweb-playground/packages/cli/index.js
+          PATTERN: "*.td.jsonld" 
         run: |
-          changed=$(git diff --name-only HEAD HEAD~1)
-          for file in $changed; do
-            if [[ $file == *.td.jsonld ]]; then 
+          # Get the list of changed files
+          url="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
+          changed_files=$(curl -s -X GET -G $url | jq -r '.[] | .filename')
+
+          exit_code=0
+          for file in $changed_files; do
+            echo "===================="
+            # Check the file extension
+            if [[ $file == $PATTERN ]]; then 
               echo 'Validating' $file '...'
-              result=$(node thingweb-playground/packages/cli/index.js $file)
+              result=$(node $VALIDATION_SCRIPT $file)
               if [[ $result == *"'failed'"* ]]; then
                 echo "$result"
-                echo 'Validation failed ✗'
-                exit 1
+                echo '::error::Validation failed ✗'
+                exit_code=1
               else
                 echo "$result"
                 echo 'Validation passed ✓'
@@ -57,5 +55,4 @@ jobs:
               echo 'Skipped' $file
             fi
           done
-
-      
+          exit $exit_code
